services:
    acav_rdstation:
        build:
            context: .
        ports:
            - "8085:8002"
        volumes:
            - .:/var/www/html
        environment:
            APP_PORT: 8002
            APP_URL: http://localhost:8085
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql

    mysql:
        image: 'mysql:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            TZ: 'America/Sao_Paulo'
            LANG: 'pt_BR.UTF-8'
            LC_ALL: 'pt_BR.UTF-8'
            MYSQL_CHARACTER_SET_SERVER: 'utf8mb4'
            MYSQL_COLLATION_SERVER: 'utf8mb4_unicode_ci'
        volumes:
            - 'sail-mysql:/var/lib/mysql'

volumes:
    sail-mysql:
